version: '3.4'

services:
  taskmanagementui:
    image: ${DOCKER_REGISTRY-}taskmanagementui
    container_name: taskmanagementui
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=staging
    ports:
      - 8087:80
